Env based deployment

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -13,14 +13,32 @@ jobs:
         id-token: write
         contents: read
     steps:
+      - name: Set environment-specific branch
+        id: set_branch
+        run: |
+          case "${{ github.event.inputs.environment }}" in
+            acceptance)
+              echo "branch=ENV-Acceptance" >> $GITHUB_OUTPUT
+              echo "AWS_ACCOUNT=${{ vars.ACCEPTANCE_ACCOUNT }}" >> $GITHUB_OUTPUT
+              ;;
+            production)
+              echo "branch=ENV-Prod" >> $GITHUB_OUTPUT
+              echo "AWS_ACCOUNT=${{ vars.PROD_ACCOUNT }}" >> $GITHUB_OUTPUT
+              ;;
+            *)
+              echo "Invalid environment" && exit 1
+              ;;
+          esac
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ steps.set_branch.outputs.branch }}
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
       - name: Configure AWS credentials using OIDC
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          role-to-assume: arn:aws:iam::646738440247:role/github-terraform-role
+          role-to-assume: arn:aws:iam::${{ steps.set_branch.outputs.AWS_ACCOUNT }}:role/github-terraform-role
           aws-region: us-east-1
       - name: Terraform Init
         run: terraform init -backend-config=backend-${{ github.event.inputs.environment }}.hcl
@@ -44,8 +62,24 @@ jobs:
       id-token: write
       contents: read
     steps:
+      - name: Set environment-specific branch
+        id: set_branch
+        run: |
+          case "${{ github.event.inputs.environment }}" in
+            acceptance)
+              echo "branch=ENV-Acceptance" >> $GITHUB_OUTPUT
+              ;;
+            production)
+              echo "branch=ENV-Prod" >> $GITHUB_OUTPUT
+              ;;
+            *)
+              echo "Invalid environment" && exit 1
+              ;;
+          esac
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ steps.set_branch.outputs.branch }}
       - name: Show current Git branch
         run: |
           echo "Branch from Git:"
